### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by AlbertDijksma** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#140]
Hi,
I see something strange happening.
The SPA is on but the pumps and heating are off.
Still I see the pump and air times slowly increasing.
I see this happening in the debug log as well.
![Screenshot_20211030-200206_Samsung Internet](https://user-images.githubusercontent.com/25565832/139553988-f8951a34-0a60-46a2-8bbf-74d10dccfa40.jpg)
![Screenshot_20211030-200239_Samsung Internet](https://user-images.githubusercontent.com/25565832/139553997-a75a50f3-7e96-4909-81f6-92e1a26c2635.jpg)

debug.html:20 {"CONTENT":"TIMES","TIME":1635616932,"CLTIME":1634405731,"FTIME":1634405733,"UPTIME":48529,"PUMPTIME":199,"HEATINGTIME":0,"AIRTIME":104,"JETTIME":0,"COST":0.013071,"FINT":30,"CLINT":14}
debug.html:20 {"CONTENT":"OTHER","MQTT":0,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":0,"FLT":0,"TGT":38,"TMP":13,"CH1":32,"CH2":49,"CH3":51,"HJT":0}
debug.html:20 {"CONTENT":"TIMES","TIME":1635616934,"CLTIME":1634405731,"FTIME":1634405733,"UPTIME":48531,"PUMPTIME":199,"HEATINGTIME":0,"AIRTIME":104,"JETTIME":0,"COST":0.013071,"FINT":30,"CLINT":14}
debug.html:20 {"CONTENT":"OTHER","MQTT":0,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":0,"**FLT":0**,"TGT":38,"TMP":13,"CH1":32,"CH2":49,"CH3":51,"HJT":0}
debug.html:20 {"CONTENT":"TIMES","TIME":1635616936,"CLTIME":1634405731,"FTIME":1634405733,"UPTIME":48533,"PUMPTIME":199,"HEATINGTIME":0,"AIRTIME":104,"JETTIME":0,"COST":0.013071,"FINT":30,"CLINT":14}
debug.html:20 {"CONTENT":"OTHER","MQTT":0,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":0,"PWR":0,"UNT":0,"AIR":0,"GRN":0,"RED":0,"**FLT":1**,"TGT":38,"TMP":0,"CH1":32,"CH2":32,"CH3":32,"HJT":0}
debug.html:20 {"CONTENT":"TIMES","TIME":1635616937,"CLTIME":1634405731,"FTIME":1634405733,"UPTIME":48534,"**PUMPTIME":199**,"HEATINGTIME":0,"AIRTIME":104,"JETTIME":0,"COST":0.013071,"FINT":30,"CLINT":14}
debug.html:20 {"CONTENT":"OTHER","MQTT":0,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":0,"**FLT":0**,"TGT":38,"TMP":13,"CH1":32,"CH2":49,"CH3":51,"HJT":0}
debug.html:20 {"CONTENT":"TIMES","TIME":1635616938,"CLTIME":1634405731,"FTIME":1634405733,"UPTIME":48535,"**PUMPTIME":200**,"HEATINGTIME":0,"AIRTIME":104,"JETTIME":0,"COST":0.013074,"FINT":30,"CLINT":14}
debug.html:20 {"CONTENT":"OTHER","MQTT":0,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":0,"FLT":0,"TGT":38,"TMP":13,"CH1":32,"CH2":49,"CH3":51,"HJT":0}
debug.html:20 {"CONTENT":"TIMES","TIME":1635616938,"CLTIME":1634405731,"FTIME":1634405733,"UPTIME":48535,"PUMPTIME":200,"HEATINGTIME":0,"AIRTIME":104,"JETTIME":0,"COST":0.013074,"FINT":30,"CLINT":14}
debug.html:20 {"CONTENT":"OTHER","MQTT":0,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":0,"FLT":0,"TGT":38,"TMP":13,"CH1":32,"CH2":49,"CH3":51,"HJT":0}
debug.html:20 {"CONTENT":"TIMES","TIME":1635616940,"CLTIME":1634405731,"FTIME":1634405733,"UPTIME":48537,"PUMPTIME":200,"HEATINGTIME":0,"AIRTIME":104,"JETTIME":0,"COST":0.013075,"FINT":30,"CLINT":14}
debug.html:20 {"CONTENT":"OTHER","MQTT":0,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":0,"FLT":0,"TGT":38,"TMP":13,"CH1":32,"CH2":49,"CH3":51,"HJT":0}
debug.html:20 {"CONTENT":"TIMES","TIME":1635616942,"CLTIME":1634405731,"FTIME":1634405733,"UPTIME":48539,"PUMPTIME":200,"HEATINGTIME":0,"AIRTIME":104,"JETTIME":0,"COST":0.013075,"FINT":30,"CLINT":14}

**Comment by visualapproach** [comment]
Hmm. See if it does this in the latest dev version also. I suspect glitches in the communication that may add up over time. I made some small changes that hopefully improves this.

**Comment by AlbertDijksma** [comment]
Hi,
Running now on dev and see the same glitches
![image](https://user-images.githubusercontent.com/25565832/139575243-56ac2960-94dc-48ed-a1f5-d554fed82120.png)

**Comment by visualapproach** [comment]
Okay I'll see if I can do something.

**Comment by visualapproach** [comment]
I pushed a fix to what I believe was the problem. (Dev version)

**Comment by AlbertDijksma** [comment]
Sorry still the same problem.
But found another strange problem.
I think it worked in the official release.
The Unit button on the spa has stopped working. (works remotely)
Is the debug log did I first press the unlock button 0100 ?
And then press the Unit button a few times. 0809 ?

debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707235,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20368,"PUMPTIME":19437,"HEATINGTIME":365,"AIRTIME":123,"JETTIME":0,"COST":0.134176,"FINT":30,"CLINT":14,"KWH":0.447254,"TTTT":-1350}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707237,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20370,"PUMPTIME":19439,"HEATINGTIME":367,"AIRTIME":123,"JETTIME":0,"COST":0.1345,"FINT":30,"CLINT":14,"KWH":0.448333,"TTTT":-1352}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707239,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20372,"PUMPTIME":19441,"HEATINGTIME":369,"AIRTIME":123,"JETTIME":0,"COST":0.134824,"FINT":30,"CLINT":14,"KWH":0.449412,"TTTT":-1354}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707241,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20374,"PUMPTIME":19443,"HEATINGTIME":371,"AIRTIME":123,"JETTIME":0,"COST":0.135147,"FINT":30,"CLINT":14,"KWH":0.450491,"TTTT":-1356}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707243,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20376,"PUMPTIME":19445,"HEATINGTIME":373,"AIRTIME":123,"JETTIME":0,"COST":0.135471,"FINT":30,"CLINT":14,"KWH":0.45157,"TTTT":-1358}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707245,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20378,"PUMPTIME":19447,"HEATINGTIME":375,"AIRTIME":123,"JETTIME":0,"COST":0.135795,"FINT":30,"CLINT":14,"KWH":0.452649,"TTTT":-1360}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707247,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20380,"PUMPTIME":19449,"HEATINGTIME":377,"AIRTIME":123,"JETTIME":0,"COST":0.136118,"FINT":30,"CLINT":14,"KWH":0.453728,"TTTT":-1362}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707247,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20380,"PUMPTIME":19449,"HEATINGTIME":377,"AIRTIME":123,"JETTIME":0,"COST":0.136118,"FINT":30,"CLINT":14,"KWH":0.453728,"TTTT":-1362}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707248,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20381,"PUMPTIME":19450,"HEATINGTIME":377,"AIRTIME":123,"JETTIME":0,"COST":0.136122,"FINT":30,"CLINT":14,"KWH":0.453739,"TTTT":-1363}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707249,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20382,"PUMPTIME":19451,"HEATINGTIME":378,"AIRTIME":123,"JETTIME":0,"COST":0.136284,"FINT":30,"CLINT":14,"KWH":0.454279,"TTTT":-1364}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707251,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20384,"PUMPTIME":19453,"HEATINGTIME":380,"AIRTIME":123,"JETTIME":0,"COST":0.136607,"FINT":30,"CLINT":14,"KWH":0.455358,"TTTT":-1366}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707253,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20386,"PUMPTIME":19455,"HEATINGTIME":382,"AIRTIME":123,"JETTIME":0,"COST":0.136931,"FINT":30,"CLINT":14,"KWH":0.456437,"TTTT":-1368}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707255,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20388,"PUMPTIME":19457,"HEATINGTIME":384,"AIRTIME":123,"JETTIME":0,"COST":0.137255,"FINT":30,"CLINT":14,"KWH":0.457516,"TTTT":-1370}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707257,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20390,"PUMPTIME":19459,"HEATINGTIME":386,"AIRTIME":123,"JETTIME":0,"COST":0.137578,"FINT":30,"CLINT":14,"KWH":0.458594,"TTTT":-1372}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707259,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20392,"PUMPTIME":19461,"HEATINGTIME":388,"AIRTIME":123,"JETTIME":0,"COST":0.137902,"FINT":30,"CLINT":14,"KWH":0.459673,"TTTT":-1374}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707261,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20394,"PUMPTIME":19463,"HEATINGTIME":390,"AIRTIME":123,"JETTIME":0,"COST":0.138226,"FINT":30,"CLINT":14,"KWH":0.460752,"TTTT":-1376}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707263,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20396,"PUMPTIME":19465,"HEATINGTIME":392,"AIRTIME":123,"JETTIME":0,"COST":0.138549,"FINT":30,"CLINT":14,"KWH":0.461831,"TTTT":-1378}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"0100","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":0,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707264,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20397,"PUMPTIME":19466,"HEATINGTIME":394,"AIRTIME":123,"JETTIME":0,"COST":0.13887,"FINT":30,"CLINT":14,"KWH":0.462898,"TTTT":-1379}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"0100","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":0,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707265,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20398,"PUMPTIME":19467,"HEATINGTIME":394,"AIRTIME":123,"JETTIME":0,"COST":0.138873,"FINT":30,"CLINT":14,"KWH":0.46291,"TTTT":-1380}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":0,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707267,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20400,"PUMPTIME":19469,"HEATINGTIME":396,"AIRTIME":123,"JETTIME":0,"COST":0.139197,"FINT":30,"CLINT":14,"KWH":0.463989,"TTTT":-1382}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":0,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707269,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20402,"PUMPTIME":19471,"HEATINGTIME":398,"AIRTIME":123,"JETTIME":0,"COST":0.13952,"FINT":30,"CLINT":14,"KWH":0.465068,"TTTT":-1384}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"0809","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":0,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707271,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20404,"PUMPTIME":19473,"HEATINGTIME":400,"AIRTIME":123,"JETTIME":0,"COST":0.139844,"FINT":30,"CLINT":14,"KWH":0.466147,"TTTT":-1386}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"0809","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":0,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707273,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20406,"PUMPTIME":19475,"HEATINGTIME":402,"AIRTIME":123,"JETTIME":0,"COST":0.140168,"FINT":30,"CLINT":14,"KWH":0.467226,"TTTT":-1388}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":0,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707275,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20408,"PUMPTIME":19477,"HEATINGTIME":404,"AIRTIME":123,"JETTIME":0,"COST":0.140491,"FINT":30,"CLINT":14,"KWH":0.468304,"TTTT":-1390}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"0809","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":0,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707277,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20410,"PUMPTIME":19479,"HEATINGTIME":406,"AIRTIME":123,"JETTIME":0,"COST":0.140815,"FINT":30,"CLINT":14,"KWH":0.469383,"TTTT":-1392}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"0809","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":0,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707279,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20412,"PUMPTIME":19481,"HEATINGTIME":408,"AIRTIME":123,"JETTIME":0,"COST":0.141139,"FINT":30,"CLINT":14,"KWH":0.470462,"TTTT":-1394}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":0,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707281,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20414,"PUMPTIME":19483,"HEATINGTIME":410,"AIRTIME":123,"JETTIME":0,"COST":0.141462,"FINT":30,"CLINT":14,"KWH":0.471541,"TTTT":-1396}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"0809","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":0,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707283,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20416,"PUMPTIME":19485,"HEATINGTIME":412,"AIRTIME":123,"JETTIME":0,"COST":0.141786,"FINT":30,"CLINT":14,"KWH":0.47262,"TTTT":-1398}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"0809","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":0,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707285,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20418,"PUMPTIME":19487,"HEATINGTIME":414,"AIRTIME":123,"JETTIME":0,"COST":0.14211,"FINT":30,"CLINT":14,"KWH":0.473699,"TTTT":-1400}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":0,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707287,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20420,"PUMPTIME":19489,"HEATINGTIME":416,"AIRTIME":123,"JETTIME":0,"COST":0.142433,"FINT":30,"CLINT":14,"KWH":0.474778,"TTTT":-1402}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":0,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707289,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20422,"PUMPTIME":19491,"HEATINGTIME":418,"AIRTIME":123,"JETTIME":0,"COST":0.142757,"FINT":30,"CLINT":14,"KWH":0.475857,"TTTT":-1404}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":0,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707291,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20424,"PUMPTIME":19493,"HEATINGTIME":420,"AIRTIME":123,"JETTIME":0,"COST":0.143081,"FINT":30,"CLINT":14,"KWH":0.476936,"TTTT":-1406}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":0,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707293,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20426,"PUMPTIME":19495,"HEATINGTIME":422,"AIRTIME":123,"JETTIME":0,"COST":0.143404,"FINT":30,"CLINT":14,"KWH":0.478014,"TTTT":-1408}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}
debug.html:20 {"CONTENT":"STATES","LCK":0,"PWR":1,"UNT":1,"AIR":0,"GRN":0,"RED":1,"FLT":1,"TGT":38,"TMP":38,"CH1":32,"CH2":51,"CH3":56,"HJT":0,"BRT":2}
debug.html:20 {"CONTENT":"TIMES","TIME":1635707295,"CLTIME":1635687912,"FTIME":1635687910,"UPTIME":20428,"PUMPTIME":19497,"HEATINGTIME":424,"AIRTIME":123,"JETTIME":0,"COST":0.143728,"FINT":30,"CLINT":14,"KWH":0.479093,"TTTT":-1410}
debug.html:20 {"CONTENT":"OTHER","MQTT":-1,"PressedButton":"1b1b","HASJETS":0}

**Comment by visualapproach** [comment]
Haha, it's actually a feature, not a bug! No I'm not kidding you. You can disable buttons on the display, to use them for better things. I have disabled my unit and timer buttons, and use them to open/close my awnings when in the spa :-). The device disables the original functions, but sends the button press over MQTT so your home automation can do whatever it wants.

Edit line 77 in BWC_8266_globals.h. Change the zeroes to ones
`const uint8_t EnabledButtons[] = {1,1,0,1,0,1,1,1,1,1,1};`

**Comment by AlbertDijksma** [comment]
Awesome,
Now I can use those buttons for something else to call my wife for a glass of wine

**Comment by visualapproach** [comment]
Yes, and when you press bubbles, she brings champagne 🍾

**Comment by visualapproach** [comment]
@AlbertDijksma I can confirm I also see this behaviour. I logged it for a couple of hours and only gained one second and only on the pumptime. I think communication glitches from the CIO might accumulate over time. When I hacked the protocol I noticed the CIO was kind of sloppy with the timings, but maybe that was my setup. The glitches has to persistent over two messages in a row to affect the ESP so it's a little bit strange. It can ofc be rounding errors or similar. I have some ideas how to improve it when I get time.

**Comment by AlbertDijksma** [comment]
What you should keep in mind is that the esp8266 only has 1 core.
The wifi part of the esp requires a lot of interrupts.
Could this be the problem?

**Comment by visualapproach** [comment]
@AlbertDijksma Maybe, if it delays my own interrupts used to read data from CIO. But anyhow, I made some small changes if you would like to try. I haven't got any increased numbers in an hour of testing now.

**Comment by AlbertDijksma** [comment]
You are great,
Now running for 2 hours and none glitches

**Comment by visualapproach** [comment]
Lovely! Thanks for reporting and testing!
